### ISSUE TITLE
TagQuerySet inquiry

### ISSUE THREAD

**Issue by jholms** [funkybob/django-lazy-tags#2]
I am still a novice at some of the Django things. 
How would I implement the TagQuerySet? Could you provide me with a few examples? And do I need to import anything into my views?

**Comment by jholms** [comment]
As well, how would I use the managers.py file? Thanks for taking the time to review.

**Comment by funkybob** [comment]
You can use the TagQuerySet like any other, and you can use as_manager() to make a manager for your models: https://docs.djangoproject.com/en/1.10/ref/models/querysets/#as-manager

I just added this to the README...

**Comment by jholms** [comment]
Okay great, thanks.
